#%RAML 1.0 DataType
properties:
  accountNum:
    type: string
    required: true
    maxLength: 10
    minLength: 10
  atmPin:
    type: string
    required: true
    maxLength: 4
    minLength: 4  
  ifscCode:
    type: string
    required: true
    maxLength: 10
    minLength: 4 
  depositAmount:
    type: number
    required: false 
  mailId:
    type: string
    required: true
  contact:
    type: string
    required: true  