#%RAML 1.0 DataType
properties:
  accountNum:
    type: string
    required: true
    maxLength: 10
    minLength: 10
  atmPin:
    type: string
    required: true
    maxLength: 4
    minLength: 4 
  amountToBeWithDraw:
    type: number
    required: true  
